import type { Metadata } from "next";
import "../styles/globals.css";
import { AuthProvider } from "./../contexts/AuthContext";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Hotel Solution",
  icons: {  icon: "/favicon.ico" },

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
    <body>
    <Toaster position="top-right" richColors />
      <AuthProvider>
          {children}
      </AuthProvider>
    </body>
    </html>
  );
}
