import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Hotel Solution",
  icons: {  icon: "/favicon.ico" },

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>

      <Header/>
        {children}
      </body>
    </html>
  );
}
